import type { Ubicacion } from './types';

export const SHELF_MODULE_WIDTH = 1.0;
export const SHELF_DEPTH = 0.45;

export const generateInitialState = (): { ubicaciones: Record<string, Ubicacion>, geometry: { x: number; y: number }[] } => {

        const geometryFinal = [
                {
                        x: 0,
                        y: 0
                },
                {
                        x: 8.15,
                        y: 0
                },
                {
                        x: 10.123777578084171,
                        y: 26.945009114327945
                },
                {
                        x: -0.8602329973537217,
                        y: 27.000000000000004
                }
        ];

        const ubicaciones: Record<string, Ubicacion> = {
                "1": {
                        id: "1",
                        tipo: "palet",
                        programa: "Vacio",
                        contenido: "1",
                        x: 0.26,
                        y: 15.25,
                        rotation: 88.18,
                        width: 0.8,
                        depth: 1.2
                },
                "2": {
                        id: "2",
                        tipo: "palet",
                        programa: "Vacio",
                        contenido: "2",
                        x: 0.29,
                        y: 14.3,
                        rotation: 88.18,
                        width: 0.8,
                        depth: 1.2
                },
                "3": {
                        id: "3",
                        tipo: "palet",
                        programa: "Vacio",
                        contenido: "3",
                        x: 0.32,
                        y: 13.35,
                        rotation: 88.18,
                        width: 0.8,
                        depth: 1.2
                },
                "4": {
                        id: "4",
                        tipo: "palet",
                        programa: "Vacio",
                        contenido: "4",
                        x: 0.35,
                        y: 12.4,
                        rotation: 88.18,
                        width: 0.8,
                        depth: 1.2
                },
                "5": {
                        id: "5",
                        tipo: "palet",
                        programa: "Vacio",
                        contenido: "5",
                        x: 0.38,
                        y: 11.45,
                        rotation: 88.18,
                        width: 0.8,
                        depth: 1.2
                },
                "6": {
                        id: "6",
                        tipo: "palet",
                        programa: "Vacio",
                        contenido: "6",
                        x: 0.41,
                        y: 10.5,
                        rotation: 88.18,
                        width: 0.8,
                        depth: 1.2
                },
                "7": {
                        id: "7",
                        tipo: "palet",
                        programa: "Vacio",
                        contenido: "7",
                        x: 0.44,
                        y: 9.55,
                        rotation: 88.18,
                        width: 0.8,
                        depth: 1.2
                },
                "8": {
                        id: "8",
                        tipo: "palet",
                        programa: "Vacio",
                        contenido: "8",
                        x: 0.47,
                        y: 8.6,
                        rotation: 88.18,
                        width: 0.8,
                        depth: 1.2
                },
                "9": {
                        id: "9",
                        tipo: "palet",
                        programa: "Vacio",
                        contenido: "9",
                        x: 0.5,
                        y: 7.65,
                        rotation: 88.18,
                        width: 0.8,
                        depth: 1.2
                },
                "10": {
                        id: "10",
                        tipo: "palet",
                        programa: "Vacio",
                        contenido: "10",
                        x: 0.53,
                        y: 6.7,
                        rotation: 88.18,
                        width: 0.8,
                        depth: 1.2
                },
                "11": {
                        id: "11",
                        tipo: "palet",
                        programa: "Vacio",
                        contenido: "11",
                        x: 0.56,
                        y: 5.75,
                        rotation: 88.18,
                        width: 0.8,
                        depth: 1.2
                },
                "12": {
                        id: "12",
                        tipo: "palet",
                        programa: "Vacio",
                        contenido: "12",
                        x: 0.59,
                        y: 4.8,
                        rotation: 88.18,
                        width: 0.8,
                        depth: 1.2
                },
                "13": {
                        id: "13",
                        tipo: "palet",
                        programa: "Vacio",
                        contenido: "13",
                        x: 0.62,
                        y: 3.85,
                        rotation: 88.18,
                        width: 0.8,
                        depth: 1.2
                },
                "14": {
                        id: "14",
                        tipo: "palet",
                        programa: "Vacio",
                        contenido: "14",
                        x: 0.65,
                        y: 2.9,
                        rotation: 88.18,
                        width: 0.8,
                        depth: 1.2
                },
                "15": {
                        id: "15",
                        tipo: "palet",
                        programa: "Vacio",
                        contenido: "15",
                        x: 0.68,
                        y: 1.95,
                        rotation: 88.18,
                        width: 0.8,
                        depth: 1.2
                },
                "16": {
                        id: "16",
                        tipo: "palet",
                        programa: "Vacio",
                        contenido: "16",
                        x: 0.71,
                        y: 1.0,
                        rotation: 88.18,
                        width: 0.8,
                        depth: 1.2
                },
                "17": {
                        id: "17",
                        tipo: "palet",
                        programa: "Vacio",
                        contenido: "17",
                        x: 1.9,
                        y: 0.85,
                        rotation: 0,
                        width: 0.8,
                        depth: 1.2
                },
                "18": {
                        id: "18",
                        tipo: "palet",
                        programa: "Vacio",
                        contenido: "18",
                        x: 2.8,
                        y: 0.85,
                        rotation: 0,
                        width: 0.8,
                        depth: 1.2
                },
                "19": {
                        id: "19",
                        tipo: "palet",
                        programa: "Vacio",
                        contenido: "19",
                        x: 3.7,
                        y: 0.85,
                        rotation: 0,
                        width: 0.8,
                        depth: 1.2
                },
                "20": {
                        id: "20",
                        tipo: "palet",
                        programa: "Vacio",
                        contenido: "20",
                        x: 4.6,
                        y: 0.85,
                        rotation: 0,
                        width: 0.8,
                        depth: 1.2
                },
                "21": {
                        id: "21",
                        tipo: "palet",
                        programa: "Vacio",
                        contenido: "21",
                        x: 5.5,
                        y: 0.85,
                        rotation: 0,
                        width: 0.8,
                        depth: 1.2
                },
                "22": {
                        id: "22",
                        tipo: "palet",
                        programa: "Vacio",
                        contenido: "22",
                        x: 6.4,
                        y: 0.85,
                        rotation: 0,
                        width: 0.8,
                        depth: 1.2
                },
                "23": {
                        id: "23",
                        tipo: "palet",
                        programa: "Vacio",
                        contenido: "23",
                        x: 7.3,
                        y: 0.85,
                        rotation: 0,
                        width: 0.8,
                        depth: 1.2
                },
                "24": {
                        id: "24",
                        tipo: "palet",
                        programa: "Vacio",
                        contenido: "24",
                        x: 7.546504,
                        y: 2.0,
                        rotation: 94.19,
                        width: 0.8,
                        depth: 1.2
                },
                "25": {
                        id: "25",
                        tipo: "palet",
                        programa: "Vacio",
                        contenido: "25",
                        x: 7.622574,
                        y: 3.038462,
                        rotation: 94.19,
                        width: 0.8,
                        depth: 1.2
                },
                "26": {
                        id: "26",
                        tipo: "palet",
                        programa: "Vacio",
                        contenido: "26",
                        x: 7.698643,
                        y: 4.076923,
                        rotation: 94.19,
                        width: 0.8,
                        depth: 1.2
                },
                "27": {
                        id: "27",
                        tipo: "palet",
                        programa: "Vacio",
                        contenido: "27",
                        x: 7.774712,
                        y: 5.115385,
                        rotation: 94.19,
                        width: 0.8,
                        depth: 1.2
                },
                "28": {
                        id: "28",
                        tipo: "palet",
                        programa: "Vacio",
                        contenido: "28",
                        x: 7.850782,
                        y: 6.153846,
                        rotation: 94.19,
                        width: 0.8,
                        depth: 1.2
                },
                "29": {
                        id: "29",
                        tipo: "palet",
                        programa: "Vacio",
                        contenido: "29",
                        x: 7.926851,
                        y: 7.192308,
                        rotation: 94.19,
                        width: 0.8,
                        depth: 1.2
                },
                "30": {
                        id: "30",
                        tipo: "palet",
                        programa: "Vacio",
                        contenido: "30",
                        x: 8.002921,
                        y: 8.230769,
                        rotation: 94.19,
                        width: 0.8,
                        depth: 1.2
                },
                "31": {
                        id: "31",
                        tipo: "palet",
                        programa: "Vacio",
                        contenido: "31",
                        x: 8.07899,
                        y: 9.269231,
                        rotation: 94.19,
                        width: 0.8,
                        depth: 1.2
                },
                "32": {
                        id: "32",
                        tipo: "palet",
                        programa: "Vacio",
                        contenido: "32",
                        x: 8.15506,
                        y: 10.307692,
                        rotation: 94.19,
                        width: 0.8,
                        depth: 1.2
                },
                "33": {
                        id: "33",
                        tipo: "palet",
                        programa: "Vacio",
                        contenido: "33",
                        x: 8.231129,
                        y: 11.346154,
                        rotation: 94.19,
                        width: 0.8,
                        depth: 1.2
                },
                "34": {
                        id: "34",
                        tipo: "palet",
                        programa: "Vacio",
                        contenido: "34",
                        x: 8.307199,
                        y: 12.384615,
                        rotation: 94.19,
                        width: 0.8,
                        depth: 1.2
                },
                "35": {
                        id: "35",
                        tipo: "palet",
                        programa: "Vacio",
                        contenido: "35",
                        x: 8.383268,
                        y: 13.423077,
                        rotation: 94.19,
                        width: 0.8,
                        depth: 1.2
                },
                "36": {
                        id: "36",
                        tipo: "palet",
                        programa: "Vacio",
                        contenido: "36",
                        x: 8.459338,
                        y: 14.461538,
                        rotation: 94.19,
                        width: 0.8,
                        depth: 1.2
                },
                "37": {
                        id: "37",
                        tipo: "palet",
                        programa: "Vacio",
                        contenido: "37",
                        x: 8.535407,
                        y: 15.5,
                        rotation: 94.19,
                        width: 0.8,
                        depth: 1.2
                },
                "38": {
                        id: "38",
                        tipo: "palet",
                        programa: "Vacio",
                        contenido: "38",
                        x: 3.4,
                        y: 4.0,
                        rotation: 90,
                        width: 0.8,
                        depth: 1.2
                },
                "39": {
                        id: "39",
                        tipo: "palet",
                        programa: "Vacio",
                        contenido: "39",
                        x: 3.4,
                        y: 4.95,
                        rotation: 90,
                        width: 0.8,
                        depth: 1.2
                },
                "40": {
                        id: "40",
                        tipo: "palet",
                        programa: "Vacio",
                        contenido: "40",
                        x: 3.4,
                        y: 5.9,
                        rotation: 90,
                        width: 0.8,
                        depth: 1.2
                },
                "41": {
                        id: "41",
                        tipo: "palet",
                        programa: "Vacio",
                        contenido: "41",
                        x: 3.4,
                        y: 6.85,
                        rotation: 90,
                        width: 0.8,
                        depth: 1.2
                },
                "42": {
                        id: "42",
                        tipo: "palet",
                        programa: "Vacio",
                        contenido: "42",
                        x: 3.4,
                        y: 7.8,
                        rotation: 90,
                        width: 0.8,
                        depth: 1.2
                },
                "43": {
                        id: "43",
                        tipo: "palet",
                        programa: "Vacio",
                        contenido: "43",
                        x: 3.4,
                        y: 8.75,
                        rotation: 90,
                        width: 0.8,
                        depth: 1.2
                },
                "44": {
                        id: "44",
                        tipo: "palet",
                        programa: "Vacio",
                        contenido: "44",
                        x: 3.4,
                        y: 9.7,
                        rotation: 90,
                        width: 0.8,
                        depth: 1.2
                },
                "45": {
                        id: "45",
                        tipo: "palet",
                        programa: "Vacio",
                        contenido: "45",
                        x: 3.4,
                        y: 10.65,
                        rotation: 90,
                        width: 0.8,
                        depth: 1.2
                },
                "46": {
                        id: "46",
                        tipo: "palet",
                        programa: "Vacio",
                        contenido: "46",
                        x: 3.4,
                        y: 11.6,
                        rotation: 90,
                        width: 0.8,
                        depth: 1.2
                },
                "47": {
                        id: "47",
                        tipo: "palet",
                        programa: "Vacio",
                        contenido: "47",
                        x: 3.4,
                        y: 12.55,
                        rotation: 90,
                        width: 0.8,
                        depth: 1.2
                },
                "48": {
                        id: "48",
                        tipo: "palet",
                        programa: "Vacio",
                        contenido: "48",
                        x: 3.4,
                        y: 13.5,
                        rotation: 90,
                        width: 0.8,
                        depth: 1.2
                },
                "49": {
                        id: "49",
                        tipo: "palet",
                        programa: "Vacio",
                        contenido: "49",
                        x: 3.4,
                        y: 14.45,
                        rotation: 90,
                        width: 0.8,
                        depth: 1.2
                },
                "50": {
                        id: "50",
                        tipo: "palet",
                        programa: "Vacio",
                        contenido: "50",
                        x: 3.4,
                        y: 15.4,
                        rotation: 90,
                        width: 0.8,
                        depth: 1.2
                },
                "51": {
                        id: "51",
                        tipo: "palet",
                        programa: "Vacio",
                        contenido: "51",
                        x: 3.4,
                        y: 16.35,
                        rotation: 90,
                        width: 0.8,
                        depth: 1.2
                },
                "52": {
                        id: "52",
                        tipo: "palet",
                        programa: "Vacio",
                        contenido: "52",
                        x: 4.6,
                        y: 16.35,
                        rotation: 90,
                        width: 0.8,
                        depth: 1.2
                },
                "53": {
                        id: "53",
                        tipo: "palet",
                        programa: "Vacio",
                        contenido: "53",
                        x: 4.6,
                        y: 15.4,
                        rotation: 90,
                        width: 0.8,
                        depth: 1.2
                },
                "54": {
                        id: "54",
                        tipo: "palet",
                        programa: "Vacio",
                        contenido: "54",
                        x: 4.6,
                        y: 14.45,
                        rotation: 90,
                        width: 0.8,
                        depth: 1.2
                },
                "55": {
                        id: "55",
                        tipo: "palet",
                        programa: "Vacio",
                        contenido: "55",
                        x: 4.6,
                        y: 13.5,
                        rotation: 90,
                        width: 0.8,
                        depth: 1.2
                },
                "56": {
                        id: "56",
                        tipo: "palet",
                        programa: "Vacio",
                        contenido: "56",
                        x: 4.6,
                        y: 12.55,
                        rotation: 90,
                        width: 0.8,
                        depth: 1.2
                },
                "57": {
                        id: "57",
                        tipo: "palet",
                        programa: "Vacio",
                        contenido: "57",
                        x: 4.6,
                        y: 11.6,
                        rotation: 90,
                        width: 0.8,
                        depth: 1.2
                },
                "58": {
                        id: "58",
                        tipo: "palet",
                        programa: "Vacio",
                        contenido: "58",
                        x: 4.6,
                        y: 10.65,
                        rotation: 90,
                        width: 0.8,
                        depth: 1.2
                },
                "59": {
                        id: "59",
                        tipo: "palet",
                        programa: "Vacio",
                        contenido: "59",
                        x: 4.6,
                        y: 9.7,
                        rotation: 90,
                        width: 0.8,
                        depth: 1.2
                },
                "60": {
                        id: "60",
                        tipo: "palet",
                        programa: "Vacio",
                        contenido: "60",
                        x: 4.6,
                        y: 8.75,
                        rotation: 90,
                        width: 0.8,
                        depth: 1.2
                },
                "61": {
                        id: "61",
                        tipo: "palet",
                        programa: "Vacio",
                        contenido: "61",
                        x: 4.6,
                        y: 7.8,
                        rotation: 90,
                        width: 0.8,
                        depth: 1.2
                },
                "62": {
                        id: "62",
                        tipo: "palet",
                        programa: "Vacio",
                        contenido: "62",
                        x: 4.6,
                        y: 6.85,
                        rotation: 90,
                        width: 0.8,
                        depth: 1.2
                },
                "63": {
                        id: "63",
                        tipo: "palet",
                        programa: "Vacio",
                        contenido: "63",
                        x: 4.6,
                        y: 5.9,
                        rotation: 90,
                        width: 0.8,
                        depth: 1.2
                },
                "64": {
                        id: "64",
                        tipo: "palet",
                        programa: "Vacio",
                        contenido: "64",
                        x: 4.6,
                        y: 4.95,
                        rotation: 90,
                        width: 0.8,
                        depth: 1.2
                },
                "65": {
                        id: "65",
                        tipo: "palet",
                        programa: "Vacio",
                        contenido: "65",
                        x: 4.6,
                        y: 4.0,
                        rotation: 90,
                        width: 0.8,
                        depth: 1.2
                },
                "E2": {
                        id: "E2",
                        tipo: "estanteria_modulo",
                        programa: "Vacio",
                        contenido: "E2",
                        x: 4.379011328560966,
                        y: 23.86,
                        rotation: 90,
                        width: 6,
                        depth: 0.45,
                        estanteriaId: 0,
                        mensaje: "Estantería 2 (6 Módulos)",
                        labelX: 2.5198337063584435,
                        labelY: 122.6595958428652,
                        labelRot: 270,
                        labelXV: 120.14851485148509,
                        labelYV: 5.5903465346534675
                },
                "E3": {
                        id: "E3",
                        tipo: "estanteria_modulo",
                        programa: "Vacio",
                        contenido: "E3",
                        x: 1.9025392806179826,
                        y: 23.87205705918814,
                        rotation: 90,
                        width: 6,
                        depth: 0.45,
                        estanteriaId: 0,
                        mensaje: "Estantería 3 (6 Módulos)",
                        labelX: 3.6616745377703928,
                        labelY: 122.52525674441851,
                        labelRot: 270,
                        labelXV: 118.06930693069293,
                        labelYV: 5.59034653465347
                },
                "E1": {
                        id: "E1",
                        tipo: "estanteria_modulo",
                        programa: "Vacio",
                        contenido: "E1",
                        x: 6.4083516483516485,
                        y: 24.835824175824175,
                        rotation: 90,
                        width: 3,
                        depth: 0.45,
                        estanteriaId: 0,
                        mensaje: "Estantería 1 (3M)",
                        labelX: 2.7213838594143533,
                        labelY: 66.42264262988196,
                        labelRot: 270,
                        labelXV: 64.52970297029701,
                        labelYV: 4.550742574257427
                },
                "E7": {
                        id: "E7",
                        tipo: "estanteria_modulo",
                        programa: "Vacio",
                        contenido: "E7",
                        x: 0.7180215252886762,
                        y: 26.64,
                        rotation: 0,
                        width: 2,
                        depth: 0.45,
                        estanteriaId: 0,
                        mensaje: "Estantería 7 (2 Módulos)",
                        labelX: -22.330418406571034,
                        labelY: 4.066146765198246,
                        labelXV: -6.336633663366339,
                        labelYV: 18.065594059405942
                },
                "E6": {
                        id: "E6",
                        tipo: "estanteria_modulo",
                        programa: "Vacio",
                        contenido: "E6",
                        x: 3.1535463998494366,
                        y: 26.635941657732552,
                        rotation: 0,
                        width: 2,
                        depth: 0.45,
                        estanteriaId: 0,
                        mensaje: "Estantería 6 (2 Módulos)",
                        labelX: -22.128978934543735,
                        labelY: 3.394483554931032,
                        labelXV: -5.29702970297032,
                        labelYV: 20.14480198019802
                },
                "E5": {
                        id: "E5",
                        tipo: "estanteria_modulo",
                        programa: "Vacio",
                        contenido: "E5",
                        x: 5.6538457011128544,
                        y: 26.644836070301768,
                        rotation: 0,
                        width: 2,
                        depth: 0.45,
                        estanteriaId: 0,
                        mensaje: "Estantería 5 (2 Módulos)",
                        labelX: -24.076596100902915,
                        labelY: -5.605304475679063,
                        labelXV: -7.3762376237624,
                        labelYV: 19.105198019801982
                },
                "E8": {
                        id: "E8",
                        tipo: "estanteria_modulo",
                        programa: "Vacio",
                        contenido: "E8",
                        x: -0.17,
                        y: 24.65,
                        rotation: 358,
                        width: 1,
                        depth: 0.45,
                        estanteriaId: 0,
                        mensaje: "Estantería 8 (1 Módulo)",
                        labelX: -5.792709751338942,
                        labelY: 27.181894775926033,
                        labelRot: 0,
                        labelXV: 22.407121120040706,
                        labelYV: 3.370241207171878
                },
                "E4a": {
                        id: "E4a",
                        tipo: "estanteria_modulo",
                        programa: "Vacio",
                        contenido: "E4a",
                        x: -0.49,
                        y: 25.9,
                        rotation: 87.88,
                        width: 2,
                        depth: 0.45,
                        estanteriaId: 0,
                        mensaje: "Estantería 4a (2 Módulos)",
                        labelX: 1.941396163935087,
                        labelY: -42.79675590017259,
                        labelRot: 270,
                        labelXV: -45.22803400791438,
                        labelYV: 6.8336565422157225
                },
                "E4b": {
                        id: "E4b",
                        tipo: "estanteria_modulo",
                        programa: "Vacio",
                        contenido: "E4b",
                        x: -0.35,
                        y: 20.9,
                        rotation: 88.18,
                        width: 7,
                        depth: 0.45,
                        estanteriaId: 0,
                        mensaje: "Estantería 4b (7 Módulos)",
                        labelX: 2.748301155516231,
                        labelY: 127.13938513670307,
                        labelRot: 270,
                        labelXV: 117.96474760592724,
                        labelYV: 6.930480520362396
                },
                "van_v3": {
                        id: "van_v3",
                        tipo: "zona_carga",
                        programa: "Vacio",
                        contenido: "van_v3",
                        x: 8.12,
                        y: 20.8,
                        rotation: 94.67,
                        width: 4.971,
                        depth: 1.94
                },
                "door_v3": {
                        id: "door_v3",
                        tipo: "puerta",
                        programa: "Vacio",
                        contenido: "door_v3",
                        x: 8.35,
                        y: 27,
                        rotation: 0,
                        width: 3.3,
                        depth: 0.2
                }
        };

        return { ubicaciones, geometry: geometryFinal };
};
